### ISSUE TITLE
How can I get evil indentation to work correctly?

### ISSUE THREAD

**Issue by 3rd3** [millejoh/emacs-ipython-notebook#103]
Whenever I use `evil-indent` on a region of Python code, it simply removed all indentation, such that everything is at indentation level 0. Is there a way to fix this?

**Comment by millejoh** [comment]
Looks like the source code for evil-indent calls a function named `indent-according-to-mode`. If ein notebooks are using Mult Lang mode (check definition of parameter `Ein:notebook modes`) then evil-indent is not going to work very well since notebook buffers have a major mode of `ein:ml`.

You might be able to get this to work using MuMaMo, but this is also a bit fraught since MuMaMo is unmaintained and can be difficult to set up.

**Comment by millejoh** [comment]
Forgot to mention - you could try setting `Ein:Notebook Modes` to `Only Python`.

**Comment by 3rd3** [comment]
Where can I find this setting? `M-x customize-group ein` does not seem to exist (installed via the `ipython-notebook` layer for Spacemacs).

**Comment by millejoh** [comment]
Something is up with your spacemacs installation, then, as I have a machine running spacemacs + ipython-notebook layer and the ein customization group exists for me.

I believe the spacemacs motto is "When in doubt, nuke the `elpa/` directory."

**Comment by 3rd3** [comment]
The problem was that Spacemacs loads the layers lazily, so the variables are not loaded until one runs `ein:*`.

**Comment by 3rd3** [comment]
Thanks for your help and this great Emacs mode.
