### ISSUE TITLE
dependency for smartrep

### ISSUE THREAD

**Issue by simonpp** [millejoh/emacs-ipython-notebook#109]
Shouldn't ein depend on smartrep? I get an error message when I call ein:notebooklist-open that smartrep-define-key is not defined. When I try again it works without complaining. After installing smartrep manually, it works on the first attempt.

**Comment by millejoh** [comment]
smartrep is actually an optional dependency - check the setting of [`ein:use-smartrep`](http://millejoh.github.io/emacs-ipython-notebook/#gotchas-python-mode-el). Since not everyone is going to use this feature (I certainly don't) it does not make sense to me to make it an installation requirement.

Maybe the right place to deal with this is in the Spacemacs [layer](http://spacemacs.org/layers/+lang/ipython-notebook/README.html), which is supposed to be somewhat opinionated when it comes to package setup for the end user, though note I don't personally maintain that.
