### ISSUE TITLE
Error (websocket): in callback `on-message': error: "Format specifier doesn’t match argument type"

### ISSUE THREAD

**Issue by sam-s** [millejoh/emacs-ipython-notebook#124]
When I do `M-.` (which runs the command `ein:pytools-jump-to-source-command`), I get 

```
Error (websocket): in callback `on-message': error: "Format specifier doesn’t match argument type"
```

in buffer `*Warnings*` and the desired source file is _not_ visited despite `(or (plist-get content :text) (plist-get content :data))` in `ein-pytools.el:ein:pytools-jump-to-source` being 

```
/Users/sds/.virtualenvs/algorisk/lib/python2.7/site-packages/tweepy/binder.py
240
```

i.e., TRT.

**Comment by millejoh** [comment]
I'm trying to reproduce this on a couple different installations - one works fine and the with the other I encounter a completely unrelated error. Sigh. Globally enabling debug on error might at least get you a traceback and narrow down where the problem is actually occurring.

**Comment by millejoh** [comment]
It sounds like something is wonky with the parameter list getting passed to a format statement somewhere along the way - so my guess this is firmly ein's fault and not websocket.

During jump to source you should see something like the following in the *ein:log-all* buffer:

    [info] Jumping to the source of plt.plot... @#<buffer *ein: 8888/Demo.ipynb*>
    [info] Connected to Demo.ipynb @#<buffer pyplot.py>
    [info] Jumping to the source of plt.plot...Done @#<buffer pyplot.py>

I would expect you see at least the `[info] Jumping to the source of plt.plot...` but not the rest since you aren't jumping to the source buffer.

**Comment by sam-s** [comment]
indeed, the last line in `*ein:log-all*` is 
```
[info] Jumping to the source of st... @#<buffer *ein: 8888/twitter.ipynb*>
```
