### ISSUE TITLE
Completion of Alternative Kernels (IRkernel)

### ISSUE THREAD

**Issue by jcpetkovich** [millejoh/emacs-ipython-notebook#129]
The [IRkernel](https://github.com/IRkernel/IRkernel) has completion that works in the jupyter notebook web interface, but which does not work in ein. I get the following error when I try completion from ein:

```
[I 15:30:51.614 NotebookApp] Saving file at /Untitled.ipynb
Error in strsplit(code, "\n", fixed = TRUE) : non-character argument
```

This also kills the kernel. I know that alternative kernels aren't really supported by ein, but I'd still like to try debugging this problem.

**Comment by millejoh** [comment]
I wonder if this is happening because EIN is trying to run Python code. It should be a little smarter about how it does this, obviously. I'll see what I can do - first step will be to install IRkernel.

**Comment by millejoh** [comment]
If I run IRkernel via docker (docker run -d -p 8888:8888 jupyter/r-notebook) I can successfully create and connect to notebooks running the R kernel. It .. sort of works. I can evaluate some expressions and nothing seems to crash. A lot of things aren't working though. I can see how it would be desirable to have EIN work better with different kernels, but it will take some time and work since EIN currently does a number of tricks that rely on the underlying kernel being Python. Sounds like an interesting challenge - I chip away at this as time permits.

One other thing - could you tell me how you are trying to run completion? I can't get anything to happen (crash or otherwise) when I call ein:completer-complete.

**Comment by jcpetkovich** [comment]
Actually, I can't get it to crash through completion anymore, I'm gonna close this. But I would definitely love to use `ein` for everything, I can't really stand the web UI for very long, I've been in emacs too long. Thanks for looking into this! If you need any R help while chipping away let me know.
