### ISSUE TITLE
Markdown Mode Not Working

### ISSUE THREAD

**Issue by hnisonoff** [millejoh/emacs-ipython-notebook#138]
Whenever I switch to markdown or raw mode and execute a cell I get "No cell found at pos=nill". This issue has happened on a Mac and Linux machine.

**Comment by millejoh** [comment]
This is mostly expected behavior since markdown/raw/heading cells are note executable in the iPython notebook. The error message could be a bit more informative. We could do away with the message altogether, but I think there should be some feedback to the user in the case that EIN cannot find an codecell when the user issues a `C-c C-c` command.

**Comment by hnisonoff** [comment]
Thank you. Sorry for the confusion!

**Comment by Krisselack** [comment]
Is it possible to "run" the markdown? After reopening the notebook, the markdown changes to h1, h2, etc... But inline it remains in markdown-code.
