### ISSUE TITLE
REQUEST [error] Error (error) while connecting to http://127.0.0.1:8888/api.

### ISSUE THREAD

**Issue by lsgrep** [millejoh/emacs-ipython-notebook#14]
```
2014-12-14 19:40:44.417 [NotebookApp] Using existing profile dir: u'/Users/yusup/.ipython/profile_default'
2014-12-14 19:40:44.423 [NotebookApp] Serving local MathJax from /Users/yusup/.ipython/nbextensions/mathjax/MathJax.js at /nbextensions/mathjax/MathJax.js
2014-12-14 19:40:44.454 [NotebookApp] Serving notebooks from local directory: /work/workspace/Python/Data-Science-45min-Intros
2014-12-14 19:40:44.454 [NotebookApp] 0 active kernels
2014-12-14 19:40:44.454 [NotebookApp] The IPython Notebook is running at: http://localhost:8888/
2014-12-14 19:40:44.454 [NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
INFO:tornado.access:302 GET /tree/ (::1) 0.55ms
2014-12-14 19:41:02.771 [NotebookApp] WARNING | Notebook k-means/K-means-Clustering.ipynb is not trusted
2014-12-14 19:41:03.427 [NotebookApp] Kernel started: 10a52fc7-7b4f-41ae-aab3-8b6f43b90c66
INFO:tornado.access:302 GET / (::1) 0.75ms
WARNING:tornado.access:404 GET /tree/api (::1) 14.29ms referer=None
WARNING:tornado.access:404 GET /api (::1) 2.51ms referer=None
WARNING:tornado.access:404 GET /api (::1) 2.30ms referer=None
WARNING:tornado.access:404 GET /tree/api (::1) 1.36ms referer=None
WARNING:tornado.access:404 GET /tree/api (::1) 1.96ms referer=None
INFO:tornado.access:302 GET /tree/ (::1) 0.49ms
INFO:tornado.access:302 GET /tree/ (::1) 0.59ms
INFO:tornado.access:302 GET /tree/ (::1) 0.44ms
WARNING:tornado.access:404 GET /api (::1) 1.36ms referer=None
INFO:tornado.access:302 GET /notebooks/api (::1) 1.24ms
WARNING:tornado.access:404 GET /files/api (::1) 1.81ms referer=None
WARNING:tornado.access:404 GET /notebook/api (::1) 1.69ms referer=None
INFO:tornado.access:302 GET /notebooks/api (::1) 0.58ms
WARNING:tornado.access:404 GET /files/api (::1) 1.78ms referer=None
```

```
In [3]: %version_information numpy,scipy,matplotlib,sympy

Out[3]:
Software versions
Python 2.7.9 64bit [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.56)]
IPython 2.3.1
OS Darwin 14.0.0 x86_64 i386 64bit
numpy 1.9.1
scipy 0.14.0
matplotlib 1.4.2
sympy 0.7.6
Sun Dec 14 19:52:37 2014 CST
```

```
(add-to-list 'load-path "~/.emacs.d/einv2")
(require 'ein2)
```

**Comment by chanGimeno** [comment]
Sorry for opening again in a closed issue, but I am getting the same (or similar) problem reported here. Please, find attached the "ein-bug-report" buffer below:


## Check list

- [x] Read the "Avoiding Common Emacs Traps" section in
  https://github.com/millejoh/emacs-ipython-notebook/blob/master/CONTRIBUTING.md
- [x] Does IPython works from the web browser?
- [x] Confirm the problem was not due to badly compiled
  files by removing all the `*.elc` files from source directory of EIN and
  its dependencies.
- [x] Confirm that the libraries are loaded as expected and are at the required version.
  (You can check the location in the "System info" section below)

## Description of the problem you have
Getting the following error message in `*Messages*` when trying to open a notebooklist
```
REQUEST [error] Error (error) while connecting to http://127.0.0.1:8888/api.
ein: [error] Error (error) while opening notebook list with path 2 at the server 8888.
```

## Steps to reproduce the problem

1. In a cshell: ipython notebook --pylab &
2. M-x ein:notebooklist-open RET
3. URL or port number (default 8888): RET

## Expected output
List of IPython notebooks

## Your EIN configuration (in .emacs.d/init.el or somewhere else)
```
;; ELPA packages
(add-to-list 'load-path "~/.emacs.d/")
(add-hook 'ein:connect-mode-hook 'ein:jedi-setup)
(setq ein:use-auto-complete-superpack t)
```

## Your IPython configuration
1. What is your IPython version? (run `ipython --version`):
   1.0.0

2. How do you start IPython? (e.g., `ipython notebook --port 9999`):
   ipython notebook --pylab &

3. What is your IPython notebook port number or URL?:
   8888

## Additional information (if any)

###### CSHELL
In the shell where the command `ipython notebook --pylab &` is run, after trying 
`M-x ein:notebooklist-open RET` in emacs, one gets the following error messages:
```
(process:2695): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed
2015-01-28 20:40:44.037 [tornado.access] WARNING | 404 GET /api (127.0.0.1) 0.48ms
2015-01-28 20:40:44.123 [tornado.access] WARNING | 404 GET /api/notebooks/ (127.0.0.1) 0.24ms
```

###### `*ein:log-all*` 
```
[verbose] Error thrown: (error http 404) @#<buffer *ein:notebooklist 8888*>
[error] Error (error) while opening notebook list with path 2 at the server 8888. @#<buffer *ein:notebooklist 8888*>
```

###### IPython version
```
Information for package IPython:
--------------------------------
Repository: openSUSE-13.1-oss-Update
Name: IPython
Version: 1.0.0-2.4.3
Arch: noarch
Vendor: openSUSE
Installed: Yes
Status: up-to-date
Installed Size: 12.8 MiB
Summary: An Enhanced Interactive Python Shell
Description: 
IPython provides a replacement for the interactive python (Python)
interpreter with extra functionality.
```

## System info:

```cl
("EIN system info"
 :emacs-version
 "GNU Emacs 24.3.1 (x86_64-suse-linux-gnu, GTK+ Version 3.10.9)
 of 2014-11-12 on cloud104"
 :emacs-bzr-version nil
 :window-system x
 :emacs-variant nil
 :os
 (:uname
  "Linux arete 3.11.10-25-default #1 SMP Wed Dec 17 17:57:03 UTC 2014 (8210f77) x86_64 x86_64 x86_64 GNU/Linux
"
  :lsb-release
  "LSB Version:	n/a
Distributor ID:	openSUSE project
Description:	openSUSE 13.1 (Bottle) (x86_64)
Release:	13.1
Codename:	Bottle
")
 :image-types
 (svg imagemagick png gif tiff jpeg xpm xbm pbm postscript)
 :image-types-available
 (svg imagemagick png gif tiff jpeg xpm xbm pbm postscript)
 :request
 (:backend curl)
 :ein
 (:version "0.3"
	   :source-dir "/users/gime_se/.emacs.d/elpa/ein-20150116.2001/")
 :lib
 ((:name "websocket"
	 :path "~/.emacs.d/elpa/websocket-20141226.1957/websocket.elc"
	 :featurep t
	 :version-var websocket-version
	 :version "1.3")
  (:name "request"
	 :path "~/.emacs.d/elpa/request-20140316.417/request.elc"
	 :featurep t
	 :version-var request-version
	 :version "0.2.0")
  (:name "auto-complete"
	 :path "~/.emacs.d/elpa/auto-complete-20150124.1523/auto-complete.elc"
	 :featurep t
	 :version-var nil
	 :version nil)
  (:name "auto-complete"
	 :path "~/.emacs.d/elpa/auto-complete-20150124.1523/auto-complete.elc"
	 :featurep t
	 :version-var nil
	 :version nil)
  (:name "popup"
	 :path "~/.emacs.d/elpa/popup-20150116.1223/popup.elc"
	 :featurep t
	 :version-var popup-version
	 :version "0.5.2")
  (:name "fuzzy"
	 :path "~/.emacs.d/elpa/fuzzy-20131025.2343/fuzzy.elc"
	 :featurep nil
	 :version-var nil
	 :version nil)
  (:name "pos-tip"
	 :path "~/.emacs.d/elpa/pos-tip-20141122.512/pos-tip.elc"
	 :featurep nil
	 :version-var nil
	 :version nil)
  (:name "python"
	 :path "/usr/share/emacs/24.3/lisp/progmodes/python.elc"
	 :featurep nil
	 :version-var nil
	 :version nil)
  (:name "python-mode"
	 :path "~/.emacs.d/elpa/python-mode-20150117.955/python-mode.el"
	 :featurep nil
	 :version-var nil
	 :version nil)
  (:name "markdown-mode"
	 :path "~/.emacs.d/elpa/markdown-mode-20150121.1229/markdown-mode.elc"
	 :featurep nil
	 :version-var nil
	 :version nil)
  (:name "smartrep"
	 :path "~/.emacs.d/elpa/smartrep-20140404.1714/smartrep.elc"
	 :featurep nil
	 :version-var nil
	 :version nil)))
```

**Comment by millejoh** [comment]
Unfortunately my fork of ein only works with version of IPython > 2.0. Looks like you are running 1.0.0. Good news is that tkf's code should still work for you if you don't want to upgrade your local copy of IPython.

**Comment by chanGimeno** [comment]
Thanks for the rapid answer!
No good news :-( I tried to get back to tkf's code and it is not working any longer due to some other problems (because the different versions of the dependencies, I guess) ...

That's why, I upgraded IPython to 2.3.1 and now I am trying to get it work. Unfortunately, I am getting new errors (similar to the ones already reported in a different issue  https://github.com/tkf/emacs-ipython-notebook/issues/141, but for IPython 1.x). I'll better open a new issue.

**Comment by deweyjk** [comment]
I am also encountering the same error message while trying `ein:notebooklist-open`. Any help would be appreciated! Here is the bug report:

## Check list

- [x] Read the "Avoiding Common Emacs Traps" section in
  https://github.com/millejoh/emacs-ipython-notebook/blob/master/CONTRIBUTING.md
- [x] Does IPython works from the web browser?
- [x] Confirm the problem was not due to badly compiled
  files by removing all the `*.elc` files from source directory of EIN and
  its dependencies.
- [x] Confirm that the libraries are loaded as expected and are at the required version.
  (You can check the location in the "System info" section below)

## Description of the problem you have
The following commands produces errors:

`ein:notebooklist-login` returns
`ein: [info] Failed to login to 8888` with notebook response
`[W 14:49:54.995 NotebookApp] 405 POST / (127.0.0.1) 0.25ms referer=None`
`*ein:log-all*` result: `[info] Failed to login to 8888 @#<buffer *GNU Emacs*>`

`ein:notebooklist-open` returns
`REQUEST [error] Error (error) while connecting to http://127.0.0.1:8888/api.`
with notebook response
`[I 14:50:02.180 NotebookApp] 302 GET /api/notebooks/ (127.0.0.1) 0.93ms`

`ein:force-ipython-version-check` returns
`REQUEST [error] Error (error) while connecting to http://127.0.0.1:8888/api.`
with notebook response
`[W 14:50:40.350 NotebookApp] 404 GET /api (127.0.0.1) 2.03ms referer=None`

Changing `request-backend` to `url-retrieve` results in the following:
`ein:notebooklist-login RET RET RET` returns nothing. Notebook response:
`[I 15:59:14.539 NotebookApp] 302 POST /login (127.0.0.1) 2.80ms`
and
`ein:notebooklist-open` hangs with message `Contacting host: 127.0.0.1:8888`



## Steps to reproduce the problem

1. In shell: `jupyter notebook`
2. `M-x ein:notebooklist-login RET`
3. `M-x ein:notebooklist-open RET`
4. `M-x ein:force-ipython-version-check RET`

## Expected output
List of available notebooks

## Your EIN configuration (in .emacs.d/init.el or somewhere else)
```
(require 'ein)
(require 'ein-loaddefs)
(require 'ein-notebook)
(require 'ein-subpackages)
```

## Your IPython configuration

1. What is your IPython version? (run `ipython --version`):
   `5.1.0`
2. How do you start IPython? (e.g., `ipython notebook --port 9999`):
   `jupyter notebook`
3. What is your IPython notebook port number or URL?:
   `8888`

## Additional information (if any)
Installed emacs using homebrew: `brew cask install emacs`

Installed EIN using MELPA.

Booting up jupyter notebook using `M-x ein:jupyter-server-start` creates a usable server, but results in the same errors are above (but I can access the server from a web browser).

Tried `brew install curl` and changing `request-curl` to no avail.

Backtrace from `ein:dev-start-debug`:
```lisp
Debugger entered--Lisp error: (wrong-type-argument request-response nil)
  signal(wrong-type-argument (request-response ...))
  ein:get-response-redirect(nil)
  ein:new-content([cl-struct-ein:$content ...] #[... ...] :data (:mimetype ...))
  ein:query-contents-legacy-success("" [cl-struct-ein:$content ...] #[... ...] :data (:mimetype ...) :symbol-status success :error-thrown nil :response #10=[cl-struct-request-response ...])
  apply(ein:query-contents-legacy-success (#1="" ...))
  #[128 ...](:data (:mimetype ...) :symbol-status success :error-thrown nil :response #10=[cl-struct-request-response ...])
  apply(#[128 ...] (:data ...))
  apply(apply #[128 ...] (:data ...))
  (condition-case ...)
  request--safe-apply(#[128 ...] (:data ...))
  (progn ...)
  (if ...)
  (let* ...)
  (let ...)
  (progn ...)
  (progn ...)
  (let* ...)
  request--callback(#<killed buffer> :type "GET" :timeout 60.0 :parser ein:json-read :sync nil :success #[128 ...] :error #[128 ...] :url "http://127.0.0.1:8888/api/notebooks/" :response #10=[cl-struct-request-response ...])
  apply(request--callback #<killed buffer> #10=(:type ...))
  (progn ...)
  (let* ...)
  (cond ...)
  (let* ...)
  request--curl-callback(#<process request curl> "finished\n")
  read-event(nil t 2)
  sit-for(2)
  execute-extended-command(nil "ein:notebooklist-open" "ein:notebooklist-open")
  funcall-interactively(execute-extended-command nil "ein:notebooklist-open" "ein:notebooklist-open")
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)
```


## System info:

```cl
("EIN system info"
 :emacs-version
 "GNU Emacs 25.3.1 (x86_64-apple-darwin13.4.0, NS appkit-1265.21 Version 10.9.5 (Build 13F1911))
 of 2017-09-12"
 :emacs-bzr-version nil
 :window-system ns
 :emacs-variant nil
 :os
 (:uname
  "Darwin wm0c9-083 15.6.0 Darwin Kernel Version 15.6.0: Tue Jan  9 20:12:05 PST 2018; root:xnu-3248.73.5~1/RELEASE_X86_64 x86_64
"
  :lsb-release nil)
 :image-types
 (png gif tiff jpeg xpm xbm pbm)
 :image-types-available
 (png gif tiff jpeg xpm xbm pbm)
 :request
 (:backend curl)
 :ein
 (:version "0.13.1"
	   :source-dir "/Users/redacted/.emacs.d/elpa/ein-20180227.1408/")
 :lib
 ((:name "websocket"
	 :path "~/.emacs.d/elpa/websocket-20171113.2045/websocket.el"
	 :featurep t
	 :version-var websocket-version
	 :version "1.9")
  (:name "request"
	 :path "~/.emacs.d/elpa/request-20170131.1747/request.el"
	 :featurep t
	 :version-var request-version
	 :version "0.3.0")
  (:name "auto-complete"
	 :path "~/.emacs.d/elpa/auto-complete-20170124.1845/auto-complete.el"
	 :featurep t
	 :version-var nil
	 :version nil)
  (:name "auto-complete"
	 :path "~/.emacs.d/elpa/auto-complete-20170124.1845/auto-complete.el"
	 :featurep t
	 :version-var nil
	 :version nil)
  (:name "popup"
	 :path "~/.emacs.d/elpa/popup-20160709.729/popup.elc"
	 :featurep t
	 :version-var popup-version
	 :version "0.5.3")
  (:name "python"
	 :path "/Applications/Emacs.app/Contents/Resources/lisp/progmodes/python.elc"
	 :featurep t
	 :version-var nil
	 :version nil)))
```
