### ISSUE TITLE
Null value passed to ein:get-ipython-major-version

### ISSUE THREAD

**Issue by lev-kusanagi** [millejoh/emacs-ipython-notebook#176]
Due to the XSRF issue I've been using EIN with notebook version 4.2.1 with no problems. 

However, after upgrading to the latest version of EIN through MELPA, I got the following error when doing ein:notebooklist-open or ein:notebooklist-login

Error (wrong-type-argument number-or-marker-p ein: [warn] Null value passed to ein:get-ipython-major-version.) on query contents, try calling `ein:notebooklist-login` first...

Downgrading to the 0.12.1 release, installing it with M-x package-install-file (emacs 25.1 feature) solved this problem.

Please let me know if I can provide more information.

Thanks again for this cool piece of software!

EDIT: 0.12.1 seems to be the latest release, so I'm not sure if I downgraded at all. I'm quite certain that the latest version from MELPA has this problem, I verified it by reproducing the error on another system.

**Comment by millejoh** [comment]
This is happening because for some reason a query to the /api REST method is failing. EIN will call this method at certain points to confirm the version of the ipython/jupyter server it is conversing with. It does this more than is probably necessary, but it gets the job done well enough.

Since 12.1 I've noticed two failure modes:
 1) If the user is not authorized to access the server (i.e. authentication is enabled and a successfull call to `ein:notebooklist-login` has yet to be made).
 2) Since 12.1 ein tries to be smarter about following redirects, this unfortunately broke my caching of the ipython/jupter version queries, but I think I have it solved as of the current state of the code.

Even with the above two fixed, though, I had still been seeing the occasional error on calling `ein:get-ipython-major-version`. Ever since I pushed f1d3fbe, which seems to make the notebooklist buffer refreshes more stable, I haven't seen this error.

Unfortunately I still haven't seen XSRF issues and I have been using jupyter 4.3.1 with token authentication enabled for some time. I have a feeling I would have to recreate your environment in great detail to figure out why this isn't working for you. I'm not sure how practical that is, especially since I am a bit constrained by my work at the moment, but if you want to let me know what OS you are running and share a copy of your emacs init file I could give it a go.

**Comment by lev-kusanagi** [comment]
Hi millejoh, thank you very much for your reply. I've had this problem both in Ubuntu 16.04 with emacs 24 and Macos Sierra 10.12.3. I'll share my .emacs with you asap, I don't think I've tried to recreate this problem with a minimal init file.

**Comment by JonathanReeve** [comment]
I'm seeing this error upon any `ein:notebooklist-open`. I log in, and the login is successful, and it tells me to run `ein:notebooklist-open`. But then I get this error that tells me to log in again. I can try logging in again, and then running `ein:notebooklist-open`, but I get the same error. 

This bug makes this layer completely unusable. Emacs 25.1.1, spacemacs 0.200.9, everything else up-to-date to master.

**Comment by millejoh** [comment]
@JonathanReeve, unfortunately I am unable to reproduce the error and I have a very similar set. I will need to know more details about both your emacs and jupyter configuration to be able to debug. As a start:

1. What is output of the jupyter console (hint: might be easier if you start jupyter using `ein:jupyter-server-start` and check contents of the `*ein:jupyter-server*` buffer).
2. What request backend are you using, curl or url-retrieve? See value of `
3. What are contents of the `*ein:log-all*` buffer?

What layers do you have enabled in spacemacs? What additional configuration do you do, if any, in `dotspacemacs/user-config`?

**Comment by JonathanReeve** [comment]
Starting jupyter with `ein:jupyter-server-start` makes it work. I guess it just doesn't work if you start jupyter from a console, then log in using that token? Maybe I was doing something wrong.

**Comment by aam-at** [comment]
I tried to use `ein:jupyter-server-start` but I am still getting error `wrong-type-argument number-or-marker-p ein: [warn] Null value passed to ein:get-ipython-major-version`. Minimal spacemacs config with python and ipython layers enabled and empty user-config.

**Comment by FrostedPenguin** [comment]
I have same issues just like above.

**Comment by FrostedPenguin** [comment]
@aam-at You might want to check my solution.

It turns out that there is nothing wrong in config.
Whenever I execute `M-x ein:jupyter-server-start`, I need to gives two path(Two consecutive helm buffer).
One is called "Server Command" and  the other one is called "Notebook Directory".
I misunderstood the meaning of  "Server Command" of helm buffer so I gave some flags for jupyter server.
That was the problem. I should have given the path of jupyter executable.

After I give the path of jupyter executable as "Server Command" and the path of my jupyter notebook directory it works really well.

But every time type `/usr/local/jupyter` is cumbersome.
Is there nice way to do this? I checked the variables related to ein but nothings really related to this.
Or am I missing something?

Also whenever I start subprocess of jupyter server inside of Emacs, my browser opens with jupyer notebook tab. It is quite annoying. Is there any way that do not open my browser whenever I start jupyter server in Emacs?

**Comment by serv-inc** [comment]
These are the contents of a jupyter started via `ein:jupyter-server-start`. Emacs `GNU Emacs 25.2.2 (x86_64-pc-linux-gnu, GTK+ Version 3.18.9) of 2017-05-06`. Ubuntu.
```
[I 10:32:28.851 NotebookApp] Serving notebooks from local directory: /path
[I 10:32:28.852 NotebookApp] 0 active kernels 
[I 10:32:28.852 NotebookApp] The Jupyter Notebook is running at: http://localhost:8888/?token=353b3b328dfa8894b7c79c9830f2f3733617cb5a955420e9
[I 10:32:28.852 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 10:32:28.852 NotebookApp] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=353b3b328dfa8894b7c79c9830f2f3733617cb5a955420e9
[I 10:32:28.988 NotebookApp] 302 POST /login (127.0.0.1) 3.48ms
[W 10:32:28.989 NotebookApp] 405 POST / (127.0.0.1) 0.70ms referer=None
[I 10:32:29.163 NotebookApp] Accepting one-time-token-authenticated connection from 127.0.0.1
[W 10:32:31.420 NotebookApp] 404 GET /api/kernels/962c3e23-10d0-4ddc-a5d3-d24a0e3709f5/channels?session_id=91A0533BA869407389CA5BBBED1E2B7B (127.0.0.1): Kernel does not exist: 962c3e23-10d0-4ddc-a5d3-d24a0e3709f5
[W 10:32:31.431 NotebookApp] 404 GET /api/kernels/962c3e23-10d0-4ddc-a5d3-d24a0e3709f5/channels?session_id=91A0533BA869407389CA5BBBED1E2B7B (127.0.0.1) 132.52ms referer=None
[W 10:33:35.452 NotebookApp] Replacing stale connection: 962c3e23-10d0-4ddc-a5d3-d24a0e3709f5:91A0533BA869407389CA5BBBED1E2B7B
```

**Comment by SyrakuShaikh** [comment]
I tried @FrostedPenguin 's solution but still got the same error mentioned by @aam-at .

Then, I dug into these and found that the following commands sequences can solve my problem:

1.  in .spacemacs, set as @FrostedPenguin.
2.  `M-x ein:jupyter-server-start`
3.  `M-x ein:notebooklist-login`
4.  `M-x ein:force-ipython-version-check`
5.  `M-x ein:notebooklist-open` or in spacemacs `SPC a i n`

Hope this will help.

P.S. I'm not familiar with emacs-lisp, maybe someone could 'combine' these cmds into a single(or simpler) one?

**Comment by aam-at** [comment]
@SyrakuShaikh That fixes my problems. Thanks!

**Comment by millejoh** [comment]
The key is the call to `ein:force-ipython-version-check`. For some reason the initial call to check the version times out, or fails resulting in a null value being cached for the running server version which borks further attempts to communicate with the server. I've made a couple changes to make this more robust; don't know if it will make any difference but I'll keep this issue open so people can report back their experiences.

**Comment by diadochos** [comment]
FYI, those who are lazy calling `ein:force-ipython-version-check`:
```emacs-lisp
(with-eval-after-load "ein"
  (defun advice:ein:notebooklist-open (&rest args)
    (call-interactively 'ein:force-ipython-version-check)
    'before)
  (advice-add 'ein:notebooklist-open :before 'advice:ein:notebooklist-open))
```

**Comment by jackkamm** [comment]
Wanted to report I encounter this error, if after opening a notebook-list for one jupyter server, I try to open a second notebook-list for a second jupyter sever (which is running on a different machine and accessed through an ssh tunnel port forward). Calling `ein:force-ipython-version-check` fixed the problem.

**Comment by LouisAsh** [comment]
@millejoh I am having the same problem, with the most recent version of Spacemacs and also updated packages, under my personal laptop with Windows 10 64bits (i.e. not on a server and with all authentication ok). Any ideas on what to try next?

**Comment by millejoh** [comment]
I'm still not 100% sure why `ein:jupyter-server-start` will hang, but I will soon push a commit that adds a timeout to the call, so hopefully the call won't completely block emacs when things go wrong.

My suggestion, call `ein:jupyter-server-start`; if it times out check if there is an `*ein:jupyter-server*` buffer and if that buffer has output from a running notebook server then you should be able to manually continue the process via a call to `M-x ein:jupyter-server-login-and-open`.

I'll keep doing what I can to make this all more robust, but a lot of this is asynchronous code which is a real bugger to debug.

**Comment by LouisAsh** [comment]
@millejoh Thanks a lot for your efforts. I think real progress was made in that commit. It is still not fully robust and a bit to cumbersome to get it all working, but I was able to start the notebook and open a console. The problem now is that the console seems "frozen":

![image](https://user-images.githubusercontent.com/31366377/30007897-b4010e5e-90e6-11e7-8083-4e2d1b2de38d.png)



That is, there is no number inside "In [ ]" and nothing happens if I type in the said console. And if I try sending it code with "SPC m s b" (in Spacemacs), it still tells me that no python console is opened and that I should open through C-c C-p.

**Comment by millejoh** [comment]
Hmm. The `IP[0]` is a good sign, it means the kernel successfully started and is waiting for input. What is `SPC m s b` bound to on your system? I assume you can enter text into the worksheet cell just below the `In [ ]`? The brackets are blank because nothing has been sent to the kernel. Once you have some python code in the cell you call `ein:worksheet-execute-cell` to run the code.

You might benefit from a reading of the [official](http://millejoh.github.io/emacs-ipython-notebook/#notebook) documents and the [ipython-layer](http://spacemacs.org/layers/+lang/ipython-notebook/README.html) documents in Spacemacs.

**Comment by LouisAsh** [comment]
@millejoh Actually, while I can write just below the `In [ ]`, if press enter nothing happens. That is, it does not behave like a terminal at all. Also, nothing is sent to such terminal with "SPC m s b", which is the default binding to send the whole buffer's code to a Python terminal.

**Comment by millejoh** [comment]
Depending on the keybindings that have been set up, you should be executing either `C-c C-c` or `M-RET`. When using the spacemacs ipython-notebook layer the corresponding commands are `SPC m RET` when in transient state and `C-RET` and `S-RET` when in insert state.

The Emacs IPython Notebook is not really a python console, instead it aims to be a faithful reproduction of the [Jupyter Notebook](http://jupyter-notebook.readthedocs.io/en/latest/) interface in Emacs, with a few extra special features. You should really read up the documentation I linked above.

**Comment by LouisAsh** [comment]
@millejoh I have the corresponding parts of the documentation before posting, and some after you suggested. After I get to a console like the one in the picture I send previously, I do try using `C-c C-c` or `SPC m RET` or the other options. As recommended in the docs. But then I am told "Start a Python process first with with 'C-c C-p'".

After starting a Python process with `C-c C-p`, then I can send code with `C-c C-c`, but now it is just a regular ipython console, not linked to the Jupyter Notebooks. The problem is not about keybindings, that I can assure.

**Comment by millejoh** [comment]
Actually it very much sounds like there has been a mixup with keybindings; the behavior you describe makes it sounds like that the keybindings from `python-mode` have overwritten the keybindings set by `ein:notebook-mode`.

The commands that should be bound to the previously mentioned keybindings are `ein:worksheet-execute-cell` and `ein:worksheet-execute-cell-and-goto-next`.

My suggestion is to execute either, or both directly via `M-x ein:worksheet-execute-cell` (I'm not an evil user so not sure what the sequence there is for the equivalent to `M-x`). My suspicion is that this will work. If it doesn't look in your `*Messages*` and `*ein:log-all*` buffer for hints on what is happening.

Now, as to why `python-mode` has overtaken EIN is likely due to how your particular Emacs has been configured. I'm guessing your setup somewhere has configured a hook that ends up calling `python-mode` after you open the notebook. This is the curse and the benefit of having a system so highly configurable as is Emacs.

**Comment by maliky** [comment]
I'm trying to switch from the ipython interpreter for org to EIN because of Coursera using jupyter but I get had similar issues as above.

Then I removed all previous config to python an ipython in my init file and it was better.
I was able to load `(require 'ein)` ; `ein:notebooklist-open` the standard way (starting jupyter notbook in terminal)

Still I have the following error, 
Here the ein:log-all buffer
```
[verbose] Error thrown: (json-readtable-error) @#<buffer *scratch*>
[error] Content list call http://127.0.0.1:8888/api/contents/ failed with status parse-error. @#<buffer *scratch*>
```
I also have this in Messages
```
REQUEST [error] Error from parser ein:json-read: (json-readtable-error)
Content list call failed, maybe because curl hasn't updated it's cookie jar yet? Let's try one more time....
REQUEST [error] Error from parser ein:json-read: (json-readtable-error)
ein: [error] Content list call http://127.0.0.1:8888/api/contents/ failed with status parse-error.
```
I installed ein from MELPA, I'm running GNU Emacs 24.5.1 (x86_64-pc-linux-gnu, GTK+ Version 3.18.9) of 2017-09-20 on lcy01-07, modified by Debian

I'm sorry, this is might not be very much ein related.

**Comment by millejoh** [comment]
My best guess is that ein has failed to properly authenticate with the jupyter server. To double check this you can start jupyter from the command line without password or token authentication with the following settings:

```python
c.NotebookApp.token = ''
c.NotebookApp.password = ''
```

Then try calling `M-x ein:notebooklist-open`. You may need to call `M-x ein:force-ipython-version-check` beforehand. Even better would be to just completely restart emacs.

**Comment by maliky** [comment]
@millejoh I got it working.  Thank you.  I think my problem was with an ESS not well installed.
Works well now.  !  Sheers !

**Comment by maliky** [comment]
@millejoh  Well It is strange.  jupyter sometimes start without difficulties but sometimes I have to restart it as in the following example with freshly open emacs
```
Starting notebook server in directory: ~/formation/coursera/python-data-science/python-fundamentals/
ein: [info] Login to http://localhost:8888 complete. Now you can open notebook list by `ein:notebooklist-open'.
Blocking call to accept-process-output with quit inhibited!!
ein: [warn] Null value passed to ein:get-ipython-major-version.
Error (wrong-type-argument number-or-marker-p ein: [warn] Null value passed to ein:get-ipython-major-version.) on query contents, try calling `ein:notebooklist-login` first...
(No files need saving)
Quit
Kill jupyter server and close all open notebooks? (y or n) y
Stopped Jupyter notebook server.
Starting notebook server in directory: ~/formation/coursera/python-data-science/python-fundamentals/
Blocking call to accept-process-output with quit inhibited!! [2 times]
ein: [info] Login to http://localhost:8888 complete. Now you can open notebook list by `ein:notebooklist-open'.
ein: [info] Opened notebook list at http://localhost:8888 with path 
```

Also I have another issue when opening an iPython console C-c o  Here's my prompt 
`
[?1l[6n[?2004h[?25l[?7l[JIn [1]: [8D[8C[?12l[?25h`  How can I correct that ?
