### ISSUE TITLE
Auto close window when edit-cell-exec finished

### ISSUE THREAD

**Issue by amosbird** [millejoh/emacs-ipython-notebook#187]
Hi, how can I make the edit cell buffer window auto closed when pressing `c-c '` or `c-c c-k` ?

**Comment by millejoh** [comment]
In an ideal world (i.e. my development environment), ein should do the following things when `ein:edit-cell-exit` is called:

 1. Remove the read-only overlay of the cell in the originating worksheet/notebook buffer being edited.
 2. Save the contents of the edit cell buffer back into the original cell (unless `ein:edit-cell-abort` has been called).
 3. Call `kill-buffer` on the edit cell buffer.
 4. Switch back to the originating worksheet/notebook buffer.
 5. Set the point at the originating cell.

Step 3 should make the edit cell buffer close; I'm not sure why that isn't happening unless you have some extra advice or hooks on `kill-buffer` that cause the call to fail or something fails in `ein:edit-cell-exit` before it gets to step 3. What happens when you call `M-: kill-buffer-hook`?

**Comment by amosbird** [comment]
it's `(evil-swap-out-markers auto-revert-notify-rm-watch t)`

**Comment by millejoh** [comment]
Sorry, wrong variable. Silly me. I meant to ask, what prints out when you call `M-: kill-buffer-query-functions`?

**Comment by amosbird** [comment]
Here you are `(ein:notebook-ask-before-kill-buffer persp-kill-buffer-query-function process-kill-buffer-query-function)`

**Comment by millejoh** [comment]
That's the exact same as what I have, and for me calling `C-c '` or `C-c C-k` shows the expected behavior.

What happens when you call either `M-x ein:edit-cell-exit` or `M-x ein:edit-cell-abort` while in an edit-cell-buffer?

**Comment by amosbird** [comment]
The same as I pressed `c-c c-'` and `c-c c-k` . The window doesn't get closed.
