### ISSUE TITLE
Wired character output when using ein:console open a console soon for ipython5.

### ISSUE THREAD

**Issue by NathanielCapital** [millejoh/emacs-ipython-notebook#191]
Whenever a ipython console session is launched by using ein:console-open , the output characters are messed up, seems the emacs interpreter can not display the correct control sequence.

`^[[6n^[[JIn [1]: ^[[8D^[[8C^[[8D^[[J^[[6n^[[JIn [1]: ^[[8D^[[8C`

(Note the problem happens in ipython version 5 -- which no longer use read line but prompt-toolkit. According to true stack overflow question below, the comint mode can not handle it, but it seems ansi- term can. Maybe the underlying interpreter can be replaced with ansi-term?

**Comment by NathanielCapital** [comment]
The stackflow question :
http://emacs.stackexchange.com/questions/24453/weird-shell-output-when-using-ipython-5

Also, the error message from the minibuffer:
"^[[6n^[[0m^[[0m^[[J^[[0\
;38;5;28mIn [^[[0;38;5;10;1m1^[[0;38;5;28m]: ^[[8D^[[8C^[[0m", 100

**Comment by millejoh** [comment]
Using term or ansi-term is an interesting idea, but would mean giving up functionality that comes with having the python inferior shell. Which may not be a thing; I wouldn't know for sure since I hardly ever see a need for using the console.

Also note that there is a vigorous, ongoing discussion over at ipython/ipython#10364 over the best way to provide legacy support to tools like Emacs. Since I am lazy and just slightly too busy in my day job I am inclined too see how the discussion on ipython turns out. If they can backport support for readline into the 5.x series it will certainly make my job easier.

On the other hand it may not be too much work substitute call to term instead of `make-comint-in-buffer`, which is the fallback in the case ipython inferior shell is not available or not configured.

**Comment by millejoh** [comment]
This is [encouraging](https://ipython.readthedocs.io/en/latest/whatsnew/version6.html). Anyone had a chance to try out the 6.0rc1 for Ipython along with [rlipython](https://github.com/ipython/rlipython)?

**Comment by timehaven** [comment]
I was not getting those exact escape characters, but I got others.  Adding 

```(setenv "JUPYTER_CONSOLE_TEST" "1")``` 

to my `init.el` fixed the issue.

**Comment by xor-xor** [comment]
> Anyone had a chance to try out the 6.0rc1 for Ipython along with rlipython?

I've just tried IPython 6.4.0 + ipython_console 5.2.0  and rlipython 0.1.2, and I get this error:
```
[TerminalIPythonApp] WARNING | Subcommand `ipython console` is deprecated and will be removed in future versions.
[TerminalIPythonApp] WARNING | You likely want to use `jupyter console` in the future
The Jupyter terminal-based Console.

[ ... ]

[ZMQTerminalIPythonApp] CRITICAL | Bad config encountered during initialization:
[ZMQTerminalIPythonApp] CRITICAL | Invalid argument: '--TerminalIPythonApp.interactive_shell_class\=rlipython.TerminalInteractiveShell'
```
From the last line I can see that there's some extra quoting happening here (`\=` instead of `=`) - the command that is feeded to `run-python` in `ein:console-open` confirms this:
```
"/Users/xor-xor/tmp/env/bin/ipython console --existing /Users/xor-xor/Library/Jupyter/runtime/kernel-1eac876a-b10f-1293-ad56-c1ee5027c231.json --TerminalIPythonApp.interactive_shell_class\\=rlipython.TerminalInteractiveShell"
```
When I change `mapconcat #'shell-quote-argument` to `mapconcat 'identity` (in `ein:console-open`), the resulting command is OK (i.e. it doesn't have this extra quoting), and it actually launches the console, but with garbled output, just as @NathanielCapital reported.

But when I paste this "correct" command directly into Terminal (i.e. outside of Emacs), it seems that the `--TerminalIPythonApp...` option is being completely ignored, without any error or warning whatsoever, and the resulting console seems to be using prompt_toolkit (colors, autocomplete dropdowns etc.), which contrasts with running the aforementioned command without `console --existing...` part (it gives me the console with good old readline backend).

I don't fully understand the relation between `ipython console` and `jupyter console`, but the former will throw an error when jupyter-console package is not installed, so I guess that at this point `ipython console` is just the same command as `jupyter console`, and unfortunately, jupyter-console doesn't provide an option to plug-in rlipython (I've alredy created an issue for this: jupyter/jupyter_console#160).
