### ISSUE TITLE
Symbol's function definition is void: make-process

### ISSUE THREAD

**Issue by pascalhaakmat** [millejoh/emacs-ipython-notebook#197]
Installing ein-20170411.1509 and running `M-x ein:jupyter-server-start` I get:

`ein:jupyter-server-start: Symbol's function definition is void: make-process`

`M-x emacs-version` says: GNU Emacs 24.5.1 (x86_64-pc-linux-gnu, GTK+ Version 3.18.9) of 2016-04-17 on lgw01-04, modified by Debian

I guess `make-process` is in Emacs 25, but is there any way to get things up and running in Emacs 24.5?

**Comment by millejoh** [comment]
Yes, unfortunately ein stopped supporting Emacs 24 around v0.12.2. This wasn't exactly intentional, but it is a little late now to try to go back and undo things.

Trying to get ein:jupyter-server-start may be difficult as Emacs 24 does not really support communication with asyncronous processes - at least not as well as Emacs 25 and beyond. With all that I have going on it is unlikely I will have much time to look into this. Hopefully upgrading to Emacs 25 is not too onerous, but I understand if it isn't possible. 

Do let me know if this is something you really, really need and I will look investigate in some more detail.

**Comment by pascalhaakmat** [comment]
That's understood. Just another reason to move to Emacs 25 :)
