### ISSUE TITLE
deferred error

### ISSUE THREAD

**Issue by Edenharder** [millejoh/emacs-ipython-notebook#214]
## Check list

- [x] Read the "Avoiding Common Emacs Traps" section in
  https://github.com/millejoh/emacs-ipython-notebook/blob/master/CONTRIBUTING.md
- [x] Does IPython works from the web browser?
- [x] Confirm the problem was not due to badly compiled
  files by removing all the `*.elc` files from source directory of EIN and
  its dependencies.
- [x] Confirm that the libraries are loaded as expected and are at the required version.
  (You can check the location in the "System info" section below)

## Description of the problem you have
`M-x ein:jupyter-server-start` only opens the notebook in web browser but not in emacs. And it gives the error that
```
Starting notebook server in directory: ~/
deferred error : (wrong-type-argument stringp nil)
You can run the command ‘ein:jupyter-server-start’ with M-x ei--sta RET
deferred error : (wrong-type-argument stringp nil)
```

## Steps to reproduce the problem

1.`M-x ein:jupyter-server-start`
2.`/usr/loca/bin/jupyter`
3.`~/`

## Expected output
Open notebook in emacs while not in web browser.

## Your EIN configuration (in .emacs.d/init.el or somewhere else)
(package-initialize)
(require 'ein)
(require 'ein-loaddefs)
(require 'ein-notebook)
(require 'ein-subpackages)

## Your IPython configuration

1. What is your IPython version? (run `ipython --version`):
jupyter 4.3.0
2. How do you start IPython? (e.g., `ipython notebook --port 9999`):
jupyter notebook
3. What is your IPython notebook port number or URL?:
8888

## Additional information (if any)
Is it possible to set the default `Server Command` and `Notebook Directory`? Thus, we need not to type them every time.

## System info:

```cl
("EIN system info"
 :emacs-version
 "GNU Emacs 25.2.1 (x86_64-apple-darwin15.6.0, Carbon Version 157 AppKit 1404.47)
 of 2017-06-05"
 :emacs-bzr-version nil
 :window-system mac
 :emacs-variant nil
 :os
 (:uname
  "Darwin eden 15.6.0 Darwin Kernel Version 15.6.0: Tue Apr 11 16:00:51 PDT 2017; root:xnu-3248.60.11.5.3~1/RELEASE_X86_64 x86_64
"
  :lsb-release nil)
 :image-types
 (svg image-io imagemagick png gif tiff jpeg xpm xbm pbm)
 :image-types-available
 (svg image-io imagemagick png gif tiff jpeg xpm xbm pbm)
 :request
 (:backend curl)
 :ein
 (:version "0.13.0"
	   :source-dir "/Users/Eden/.emacs.d/elpa/ein-20170602.1905/")
 :lib
 ((:name "websocket"
	 :path "~/.emacs.d/elpa/websocket-20161113.1736/websocket.el"
	 :featurep t
	 :version-var websocket-version
	 :version "1.5")
  (:name "request"
	 :path "~/.emacs.d/elpa/request-20170131.1747/request.el"
	 :featurep t
	 :version-var request-version
	 :version "0.3.0")
  (:name "python"
	 :path
	 "/usr/local/Cellar/emacs-mac/emacs-25.2-z-mac-6.4/share/emacs/25.2/lisp/progmodes/python.elc"
	 :featurep nil
	 :version-var nil
	 :version nil)))
```

**Comment by millejoh** [comment]
What happens when you make calls to `ein:jupyter-server-login-and-open` or `ein:notebooklist-open`?

`ein:jupyter-server-start` does a several things:

 - It starts the ipython/jupyter notebook server via `make-process` in the buffer `*ein:jupyter-server*`.
 - It tries to guess when the server has finished launching and then makes a call to `ein:jupyter-server-login-and-open`.

`ein:jupyter-server-login-open` scans the server process buffer for the token login info, which looks something like:

> [I 07:14:57.959 NotebookApp] The Jupyter Notebook is running at: http://localhost:8889/?token=e679911de6d3b735254779b1e35022667d1dfca6eaef3972

And uses that information in calls to `ein:notebooklist-login` and `ein:notebooklist-open`.

I have noticed on slower machines EIN sometimes looks for the login token before the notebook server finishes launching, which breaks the process of automatically logging in and opening a notebooklist buffer. If you have token authentication disabled it is possible the code will also fail. In either case all you should need to do is manually call `ein:notebooklist-open` (well, `ein:notebooklist-login if passwords/tokens are enabled) after calling `ein:jupyter-server-start.`

**Comment by Edenharder** [comment]
`ein:jupyter-server-login-and-open` gives the error that 
```
let: Args out of range: #<buffer *ein:jupyter-server*>, 0, 1
```
while `ein:notebooklist-open` works fine. 

Yes, I have disabled the token authentication.

**Comment by visionnoob** [comment]
Just to add to the discussion.

I observed the behavior that @millejoh mentioned about EIN running out before notebook server could successfully launch. Maybe EIN waits an arbitrary amount of time rather than message passing from the server. 

I get the same deferred error sometimes. My system setup is similar to @Edenharder. Other times it works and opens the notebooks list. Nonetheless, I just run `ein:notebooklist-open` to make it work.    

> Is it possible to set the default Server Command and Notebook Directory? Thus, we need not to type them every time. 

I use this. Do not know if @millejoh plans to add default in source itself.  

```
(setq notebook-dir1 <notebookdir>)
(global-set-key (kbd "<f7>") '(lambda()
				(interactive)
				(ein:jupyter-server-start
				 (executable-find
				  "jupyter")
				 notebook-dir1)))
(global-set-key (kbd "<f8>") '(lambda()
				(interactive)
				(ein:jupyter-server-stop)))

```

**Comment by Edenharder** [comment]
Since I disabled the token authentication and the problem lies in the function `ein:jupyter-server-login-and-open`, so I comment off the part about `login` in the definition of this function. Now it works fine.

Thanks for your configuration about the keyboard shortcuts @visionnoob

**Comment by millejoh** [comment]
I've tried to improve the behavior of `ein:jupyter-server-start` in the most recent commit but only time will tell if it is effective or not.

Also, please see the customizable variables `ein:jupyter-default-server-command`, `ein:jupyter-server-args`, and `ein:jupyter-default-notebook-directory`.
