### ISSUE TITLE
[Workaround] Being able to open notebooks in subfolders

### ISSUE THREAD

**Issue by gcr** [millejoh/emacs-ipython-notebook#23]
Hello! I don't have a patch yet, but I'd like to start some discussion on how to support opening and saving notebooks that are inside subfolders.

Suppose IPython Notebook is run inside a folder with subfolders, e.g.
```
~/ipy-notebooks/
   .../Archive/
      ../Foo1.ipynb
      ../Foo2.ipynb
```

Right now, EIN has no way to open a notebook that's inside a subfolder because we assume the notebook list is flattened list and not a full filesystem hierarchy. However, this seems to be the only assumption: if you evaluate something like `(ein:notebook-open 8888 "Archive/Foo1.ipynb")`, then the notebook opens fine and you are able to evaluate things. Easy sneezy.

As a workaround, here's a (SUPER HACKY) function that you can use to just open a notebook directly:
```elisp
(defvar ein-notebook-directory "~/ipy-notebooks")   ;; TODO CHANGE THIS to your notebook folder!
(defun ein-find-notebook (port-or-url notebook-file)
  "Open a notebook file"
  (interactive
   (list (ein:notebooklist-ask-url-or-port)
         (ido-read-file-name "Open notebook: " ein-notebook-directory)))
  (let ((notebook-path (file-relative-name notebook-file ein-notebook-directory)))
    (ein:notebook-open port-or-url notebook-path)))
```
Now you can use `ein-find-notebook` in a way that's similar to `find-file`. You may have to remove the `ido` part if you don't use `ido`.

This completely sidesteps the `ein:$notebooklist` functionality though, which is a shame since now we can't delete/create notebooks.

Second issue: Saving a notebook fails. Luckily, this is a simple fix in `ein-notebook.el`:

```diff
diff --git a/lisp/ein-notebook.el b/lisp/ein-notebook.el
index 0b0cf07..43c17a9 100644
--- a/lisp/ein-notebook.el
+++ b/lisp/ein-notebook.el
@@ -606,8 +606,8 @@ of NOTEBOOK."
     (ein:events-trigger (ein:$notebook-events notebook)
                         'notebook_saving.Notebook)
     (let ((data `((content . ,content-data))))
-      (push `(path . "") data)
-      (push `(name . ,(ein:$notebook-notebook-name notebook)) data)
+      (push `(path . ,(file-name-directory (ein:$notebook-notebook-name notebook))) data)
+      (push `(name . ,(file-name-nondirectory (ein:$notebook-notebook-name notebook))) data)
       (ein:query-singleton-ajax
        (list 'notebook-save
              (ein:$notebook-url-or-port notebook)
```

With the helper function and this short change, I'm able to use EIN perfectly now, even for notebooks with subfolders.

The latter seems like a simple change. I'm not sure how to fix the notebook list though; it could require a pretty complicated refactoring, eg. rewriting the notebook list to walk the entire file hierarchy exposed by the server, or maybe something simpler like adding a current file path parameter when we open the notebook list. I'm not familiar with that part of the codebase.

**Comment by millejoh** [comment]
Glad to hear you are still getting some use out of ein, and thanks for the code suggestions. Have you tried `ein:notebooklist-open`? That handles listing directories and notebooks in subdirectories, as well as opening creating and deleting notebooks in subdirectories. I don't support creating directories (something that is in IPython 3.0), but I will get to it eventually.

I've noticied that ein:notebooklist-open-notebook-global doesn't work so well in the new world of notebooks in subdirectories and I've taken some small steps in the horribly named deferred-dev branch to fix this. Take a look at the ein-contents.el. Supporting this is important for me because otherwise the connect buffer to notebook functionality won't wokr!

I like the idea of just farming out notebook search to emacs and the filesystem, though this won't work if someone is trying to access a notebook that is hosted remotely.

I've been busier than usual lately, but I hope I can get this working not too long after the IPython devs release 2.0.

By the way, which IPython version are you using?

**Comment by gcr** [comment]
Oh my goodness. I haven't updated emacs-ipython-notebook since May 2014. I literally had no clue this was already supported.

Now I feel like an idiot! So much has improved since then! You have no idea how excited I am to try the new version out.

(I am on IPython v2.2.0, and EIN like 3b04986, which is horribly outdated by now ...)

Sorry for the spam!

**Comment by millejoh** [comment]
No problem! If it is easier for you, the ein recipe in melpa now tracks my fork instead of tkf's and might make it easier to keep up with changes to the project.

Good luck!
