### ISSUE TITLE
Dash and ein:worksheet-empty-undo-maybe

### ISSUE THREAD

**Issue by wll745881210** [millejoh/emacs-ipython-notebook#236]
Hi there, 
Two brief suggestions.

1. As of the 20170922 version, it seems that the only places where dash is used is in ein-notebooklist.el, inside the function ein:notebooklist--order-data. Is it really necessary to use dash there to sort the list? In most people's standard ELPA, dash is not available, nor is dash required when one tries to install ein there.

2. In ein-worksheet.el, the contents inside function ein:worksheet-empty-undo-maybe are commented out. This equates undo mode "yes" with "full", and you know, "full" is unstable since TKF's versions. In fact, commenting out those lines causes serious problems. By undo-ing something, one risks losing all contents inside the notebook, and this actually happens a lot of times on me and my friends using ein.

Cheers.

**Comment by heroxbd** [comment]
The change has been introduced in d57c74577fa1c1a40a2a7a17a955765a30a23258.  But cell-level undo is unstable, more than 3 of my notebooks lost 70% percent of the cells, when I hit undo and redo did not recover them.

Any hint to make a minimal reproducible example for this bug?  For the usability of EIN, we should just disable this immature features of cell-level undo by default.

**Comment by heroxbd** [comment]
Please restrict the cell-level undo feature only when ein:worksheet-enable-undo is set to 'full.

**Comment by millejoh** [comment]
I'll work on having the undo as a customizable feature - I'm sorry about the loss of data! I had tried to test it as much as possible, but clearly I missed some corner cases.

If you figure out any way to repeat the data loss I would love to hear about it.

Also, too late now, but note that EIN does save checkpoints. This feature is enabled via `ein:notebook-create-checkpoint-on-save` and frequency is determined by the `ein:notebook-autosave-frequency` variable, and you can revert to a previous checkpoint via `ein:notebook-restore-to-checkpoint`.

I do sort of want to refactor the code to use dash in general, and I figured in the MELPA age getting access to dependencies is not too big a deal. I may have figured wrong, so I will give some thought to removing dash dependency while I rethink the refactoring effort.

**Comment by dickmao** [comment]
One can readily reproduce the loss-of-data issue by simply opening an existing notebook (*CAUTION: this will result in a permanent loss of the worksheet cell, so please copy it first, or ensure it's under version control*), and mix a bunch of random edits and C-c C-c and undo's.  Eventually, the cell will disappear.

The https://github.com/millejoh/emacs-ipython-notebook/commit/d57c74577fa1c1a40a2a7a17a955765a30a23258 changes add a generous dose of `ein:worksheet-delete-cell` calls to the undo queue, which tkf indicates with some alacrity are irreversible.  In particular @millejoh, in https://github.com/millejoh/emacs-ipython-notebook/blob/27be0fd4c30f97ccbd8aab47666c47677f4a35ce/lisp/ein-worksheet.el#L794 was the idea to replicate the `cell` being executed after itself?

To avoid such losses, I merely commented out the calls to `worksheet-delete-cell` for C-c C-a, C-c C-b, and C-c C-c [here](https://github.com/dickmao/emacs-ipython-notebook/blob/52088cc95e28a32a4f92699b6c7f57d74b527639/lisp/ein-worksheet.el).

Undo's are a tricky business, particularly because they are per-buffer, and in ein's case we need them to be per-cell.

**Comment by jackkamm** [comment]
undo causing permanent loss of data in ein is a longstanding issue for me, even causing me to give up on ein before because it was just too dangerous.

The commit from @dickmao works beautifully for me and allows me to continue using this great package instead of having to switch to browser.

Hope fixing this is high-priority as it is very frustrating to permanently lose work due to accidental undo.

**Comment by millejoh** [comment]
Until I can vet and integrate @dickmao's suggested changes I have made undo of cell actions an optional (see commit 63388e5d0cf318bdb687054e2de4a4205108ed73) feature. Set `ein:worksheet-enable-undo` to nil (which is the default setting) to enable the undo. This should make ein more stable while I figure out how to clear up this self-inflicted mess.
