### ISSUE TITLE
Example of connection to console over SSH

### ISSUE THREAD

**Issue by davidpham87** [millejoh/emacs-ipython-notebook#249]
First of all, thanks a lot for your work with EIN. As jupyter notebooks seem to become the standard in data analysis, I can't express how much I appreciated EIN. Another new trend is to rent computing capacities in cloud and I am trying to use aws (following the introduction from [keras](https://blog.keras.io/running-jupyter-notebooks-on-gpu-on-aws-a-starter-guide.html)).

First of all, I think the tip about ssl connection could enhancement by bolding the "self-assigned" (or stating explicitely those created with `openssl`), and maybe create the code snippet explicitely (with an elisp function maybe?). It took a few hours to find my issue. I would gladly help, my skills in Elisp are not that great.

Concerning my main bug, that is my inability to connect to a ipython kernel started on the server, according to the documentation, the `ein:configure-security-dir` function should be called to set the folder where the `json` configuration is saved. Would it be possible to have an example? I entered the absolute path in the server but it did not work. In the best of the world, I would gladly see an example with the `ein:console-args` to make sure I don't do anything silly.

Thanks a lot for your support and please keep going!

**Comment by xor-xor** [comment]
I was trying to figure out this as well recently - turned out to be quite straightforward, although the bits of information needed to set up this stuff are scattered around in different places, so I thought that gathering them together here may be useful for others.

# Prerequisites

I assume that:

* you have an access via SSH to some remote machine where Jupyter is running;

* you have configured that access via `~/.ssh/config` on your local machine (i.e. the one where you have Emacs+EIN running), e.g.:
  ```
  Host jupyter-remote
     HostName <IP address or FQDN of this host>
     User <username that you use for logging in via SSH>
     IdentityFile <path to the private key that you use with the above username>
  ```

* you have configured your Emacs+EIN to successfully run notebooks on your remote machine.

# Setting up required variables

Having satisfied the above requirements, you need to set `ein:console-executable`, which should point to some `ipython` or `jupyter` executable available on your local machine - e.g. `(setq ein:console-executable (expand-file-name "~/envs/ein/bin/ipython"))` (this can be an arbitrary instance of `ipython` or `jupyter` from your local machine, though).

Then, you need to set `ein:console-security-dir` - you can configure it in three different ways, as a `string`, `alist` or `function` (see the output of `(describe-variable 'ein:console-security-dir)`). For simplicity, I'll use the first one - in my case (my local machine runs macOS) it is set up like this: `(setq ein:console-security-dir (expand-file-name "~/Library/Jupyter/runtime"))`, although this can be some arbitrary dir like e.g. `~/my_jupyter_connection_files` - the thing that matters here is that your local IPython or Jupyter will be looking here for so called "connection files", which are simple JSON files specifying connection parameters for a given kernel (in our case, a remote one), e.g.:
```
$ cat kernel-48adef5a-61ee-4203-96ea-4a6e54151ccb.json
{
  "signature_scheme": "hmac-sha256",
  "ip": "127.0.0.1",
  "transport": "tcp",
  "key": "3e01907e-e3cb8b471f44398e5d0666e6",
  "hb_port": 41569,
  "kernel_name": "",
  "stdin_port": 35234,
  "shell_port": 41006,
  "iopub_port": 60683,
  "control_port": 48579
}
```

OK, but how to get the connection file for remote kernel in our local security dir? There are two ways of achieving this:

* **find such file on your remote machine and copy it via `scp` to your local security dir** (remember to keep the name of this file unmodified, because the part between `kernel-` and `.json` uniquely identifies the kernel that you want to connect to!); if your remote machine runs on Linux (vast majority of cases, I guess), then this file will be located in `$XDG_RUNTIME_DIR/jupyter` (where `$XDG_RUNTIME_DIR` could be something like e.g. `/run/user/1000`); another important thing to remember here is that connection files are created only for running kernels, so if your remote Jupyter is running, but without any kernel started, you won't see any of those files in the aforementioned dirs!

* **run `%connect_info` magic command** in the notebook that you're working with remotely in EIN and just save the resulting JSON as a `kernel-<UID of the remote kernel>.json` file in your local security dir (I guess that this can be easily automated by writing some simple utility function).

Last variable to set up is `ein:console-args` - you need at least two arguments here: `--simple-prompt` and `--ssh`, e.g. `(setq ein:console-args '("--simple-prompt" "--ssh" "jupyter-remote"))` (notice that the string after `--ssh` should correspond with the `Host` from your `~/.ssh/config`!).

## Digression: the need for `--simple-prompt`

From IPython 5.x onward, there's a new readline library - prompt_toolkit - which unfortunately breaks compatibility with Emacs (at least for those using python.el, me included) - see e.g. ipython/ipython#10364, #191.

But fortunately enough, [some nice guy](https://twitter.com/ivanov/status/864918036628869124) from IPython team has extracted the good old readline library from IPython 4.x and provided it as a separate [rlipython](https://github.com/ipython/rlipython) pip package, which can be used with a new option `--TerminalIPythonApp.interactive_shell_class` (but unfortunately, this option hasn't been ported to `jupyter console` yet - see jupyter/jupyter_console#160).

So, to summarize all this - at this moment, you have the following options:

* use IPython 4.x (in `ein:console-executable`) and drop `--simple-prompt` from `ein:console-args`;

* use IPython >=5.x and keep `--simple-prompt`;

* use IPython >=5.x with rlipython installed, and change `--simple-prompt` to `--TerminalIPythonApp.interactive_shell_class=rlipython.TerminalInteractiveShell`;

* use Jupyter and keep `--simple-prompt` (I've noticed one weird issue here, which I need to investigate further, but otherwise it works OK).


# Putting it all together

Having all the above variables set up (`ein:console-executable`, `ein:console-security-dir` and `ein:console-args`), EIN will compose a command for launching the console. Following the examples given here, it may look like this:
```
/Users/xor-xor/envs/ein/bin/ipython console --existing /Users/xor-xor/Library/Jupyter/runtime/kernel-48adef5a-61ee-4203-96ea-4a6e54151ccb.json --simple-prompt --ssh jupyter-remote
```

(you can see it by yourself by stepping through the `ein:console-open` function with Emacs' own debugger [Edebug](https://www.gnu.org/software/emacs/manual/html_node/elisp/Edebug.html) - just run `M-x find-function <RET> ein:console-open`, hit `C-u C-M-x` on its definition, run it via `C-c C-o` (from notebook) and voila - you're in debugger now)

A very nice thing about the `--ssh` option is that it does **all** the work needed to set up all the required SSH tunneling - before I tried it, I was expecting some more manual work with this, but it was just a matter of hitting `C-c C-o` from my notebook, and magically, I got a nice console connected to the remote Jupyter/IPython kernel in my Emacs.

# Additional remarks

I think it would be quite handy to have the ability to specify different remote machines (i.e. the arguments for `--ssh` option) via some configuration variable like `alist` type of `ein:console-security-dir` - or better yet, merge them together, so by specifying some URL or port, you'd get not only security dir related to it, but also an argument for `--ssh`.

# References

[Cookbook: Connecting to a remote kernel via ssh](https://github.com/ipython/ipython/wiki/Cookbook:-Connecting-to-a-remote-kernel-via-ssh)
[Runtime files @ Jupyter Documentation](https://jupyter.readthedocs.io/en/latest/projects/jupyter-directories.html#runtime-files)
[Release of IPython 5.4, 6.1, and rlipython](https://blog.jupyter.org/release-of-ipython-5-4-6-1-and-rlipython-a5776b536899)

**Comment by davidpham87** [comment]
Thanks a lot for the comment!

I solved the issue a while ago using the exact same step! 


I have some trouble now to connect a remote inferior iPython process to the notebook.

**Comment by dickmao** [comment]
> Another new trend is to rent computing capacities in cloud and I am trying to use aws

A project has been entered onto the docket.
