### ISSUE TITLE
Long notebooks stall

### ISSUE THREAD

**Issue by gladomat** [millejoh/emacs-ipython-notebook#259]
I have an issue with notebooks (although I don't know if it's due to their length) that stall while editing. So I have to wait until it unfreezes so I can continue. This happens every 2nd minute and is pretty. Does anybody else have this problem?

**Comment by millejoh** [comment]
Does calling `ein:notebook-disable-autosave` stop the freezes? Saving a notebook should be done asynchronously, but this should ensure that is the case. By "Long" what do you mean? How many cells in the notebook.

The freeze might be caused by the GC. Call `M-x profiler-start`, let the notebook freeze a couple times then call `profiler-report`. Post what results. Thanks!

**Comment by gladomat** [comment]
I ran the profiler and it looks like autosave is slowing it down and executing cells also completely freezes the notebook. I've attached two profile reports.

[ein_profile_report.txt](https://github.com/millejoh/emacs-ipython-notebook/files/1698557/ein_profile_report.txt)
[ein_profile_report_2.txt](https://github.com/millejoh/emacs-ipython-notebook/files/1698558/ein_profile_report_2.txt)
