### ISSUE TITLE
(require 'mumamo) fails before nxhtml is loaded

### ISSUE THREAD

**Issue by treese** [millejoh/emacs-ipython-notebook#28]
When installing the current git version of ein, I get a compilation error on ein-mumamo.el that (require 'mumamo) fails. It appears that this is because mumamo is only on the load path after nxhtml is loaded, which is done only when needed. 

I'm not sure what the best fix is--maybe just require nxhtml? It may not matter in practice, since I think the only real problem is that ein-mumamo.el doesn't get byte-compiled. But it's always a bit distressing to see compilation errors on a package installation.

This is with Aquamacs version 3.2 on Max OS X Yosemite, which is based on Emacs 24.4.51.2.

**Comment by millejoh** [comment]
Mumamo is a problem child. nxhtml isn't actively maintained and from what I see and is not available from MELPA. I think I might confuse a lot of people if I make nxhtml a requirement. One solution would be to factor out the mumamo code into its own, optional package (ein-mumamo or some such). Another thought would be to use web-mode instead of nxhtml.

For the moment you are right that the compilation error doesn't cause any other issues with using ein that I have seen.

**Comment by treese** [comment]
Yes, it looked a bit sticky when I poked around the sources. If it's not causing any real trouble, it's fine to close this issue, although it seems quite possible that some mumamo problem could bite in the future. Thanks for looking at it.
