### ISSUE TITLE
Nodebook extension does not work

### ISSUE THREAD

**Issue by hnisonoff** [millejoh/emacs-ipython-notebook#295]
I was trying out the nodebook jupyter extension (https://github.com/stitchfix/nodebook) and realized that it seems to not work with EIN. I was curious what part of EIN prevents this extension from working. It works fine in the browser.

**Comment by millejoh** [comment]
Probably because of [this](https://github.com/stitchfix/nodebook/blob/master/nodebook/ipython/nbextensions/nodebookext.js) file. EIN has very, very limited abilities for executing javascript. EIN tries very hard to look like the Jupyter notebook, but keep in mind that the only things the two applications really have in common are that both understand how to communicate with the Jupyter server and running kernels.

That said it wouldn't be impossible to implement this sort of behavior in EIN by rewriting the javascript into some elisp equivalent. It would require some detailed knowledge of ein's internals. It would be good discipline on my part to make sure ein's internals are sufficiently documented and designed to make this easier for contributors, but who knows with my current time constraints how that will work out. In any case I'll mark this as a enhancement as it represents an interesting challenge.

**Comment by hnisonoff** [comment]
Thank you for the explanation -- that makes sense. I would certainly encourage more effort on the overall documentation than on this specific feature. I really appreciate all the great work that has gone into this project already and hope to be able to contribute back to it.

**Comment by sam-s** [comment]
I am not sure if I should create a separate issue, but the only extension I am interested so far is [`ExecuteTime`](https://jupyter-contrib-nbextensions.readthedocs.io/en/latest/nbextensions/execute_time/readme.html) and it should be relatively easy to implement in Lisp. Note that the existing `%load_ext autotime` provides the _timing_ but not the _timestamp_.

Maybe you could guide me through implementing `ExecuteTime` in lisp?

It would be sad if the only way to extend `ein` were through JavaScript.

**Comment by millejoh** [comment]
From what I can tell @tkf designed `ein`'s datastructures to somewhat mimic the Javascript code for the ipython notebook, but believe me at the end of the day `ein` is 100% elisp. Well, almost 100%, there is some dependence on Python - take a look at `ein-pytools.el`.

So, this is how I understand how `ein` renders worksheets. The cells are stored as doubly-linked list of EWOC nodes. The pp function is `ein:cell-pp` and it looks like every node has a prompt, input, output, and footer component.

If I were a clever programmer I'd probably take a look at `ein:cell-insert-footer`. Worksheet cells are EIEIO objects so it shouldn't be too hard to come up with a solution that prints out a timestamp for `ein:codecell` objects. Unfortunately EIEIO is nowhere near as awesome as CLOS, but I could probably stumble my way to a solution.

The challenge, I think, is in getting the execution times. From reading the documentation it looks like the extension patches some of the jupyter sever code from javascript. Looking at javascript makes my head hurt, but I'll take a look and see what it would take to reproduce in elisp.

**Comment by millejoh** [comment]
My mistake - the javascript doesn't patch the Python code, it adds some metadata to the messages sent to the kernel. The way to do this in `ein` would probably be to modify `ein:kernel-execute` and `ein:cell--handle-execute-reply`.

One way to do this might be to add some hooks - `ein:kernel-pre-execute-hooks` and `ein:kernel-post-execute-hooks` that would get called with the json messages sent to and received from the kernel.

**Comment by millejoh** [comment]
@sam-s, take a look at the file `ein-timestamp.el` in the most recent commit, 1e70df87d03aa7c113faadb2041683b612739aa2. If you add a `(require 'ein-timestamp)` sometime after loading `ein` you should get behavior similar to ExecuteTime.

The code definitely could use some polishing, but I suppose it could serve as prototype for how to write "extensions" for ein.
