### ISSUE TITLE
Sympy image print does not work

### ISSUE THREAD

**Issue by falematte** [millejoh/emacs-ipython-notebook#304]
Running a very minimal example like this one:
```python
from sympy import *
init_printing()
x = symbols('x')
x
```
creates a link to an image (specified in the header of the block) but does not display it automatically.

**Comment by falematte** [comment]
I am running this from an org buffer. Thank you for the answer. Changing the the `results` option it is working fine. Anyway it is not necessary for pyplots. Why?

**Comment by millejoh** [comment]
Actually, it depends. I have some situations where the plots show up with the colon in front, and sometimes they don't. EIN isn't particularly clever about handling results from executing org buffer code blocks, mostly because I'm not terribly clever about understanding all the different options org source code blocks offers.
