### ISSUE TITLE
Initialize ein when launching emacs

### ISSUE THREAD

**Issue by falematte** [millejoh/emacs-ipython-notebook#316]
I always use ein babel org blocks for doing computations. Every time, after emacs startup, I need to launch `ein-jupyter-server-start` and open a notebook. The org babel header have the link to this notebook and, therefore, can be evaluated. I tried to automate this process tweaking my `.emacs` in order to automatically launch a kernel without any luck. Any tips?

**Comment by millejoh** [comment]
You probably want to do something similar to what ob-ein does in `ein:org-find-or-open-session`, which calls `ein:notebook-open`.

Note that at the moment ein sort of treats notebooks and kernels as one thing, so if you want to start a kernel you need to open a notebook that is associated with that kernel.

For example, say you have a python 3.6 kernel that you have associated with the notebook named `Untitled.ipynb` and your jupyter server is running on localhost on port 8888. You could execute

```elisp
(ein:notebook-open "http://localhost:8888" "Untitled.ipynb")
```

Note that you should use always the full url as shown in the `*ein:jupyter-server*` buffer otherwise ein won't be able to find the right cookie for authentication.

This executes asynchronously, so you may not see the notebook open immediately depending on how fast your computer is.

If you want some additional actions to occur after the notebook is opened you can include a callback argument with the call - for an example check the code for `ein:org-find-or-open-session`.

**Comment by falematte** [comment]
Thank you for the detailed answer. I believe that I would like to do something easier. Essentialy being alway able to evaluate org ein block linked to a certain notebook/kernel. Nowadays I need to start the notebook manually. I would like to put something in my init file which can automate the whole process.

**Comment by millejoh** [comment]
Okay, I think the easiest way to do that would be to put the following in your init file:

```elisp
(require 'ein-jupyter)

(setq ein:jupyter-server-args '("--port=8888")) ;; Or whatever you prefer
(ein:jupyter-server-start "/path/to/jupyter/cmd" "/path/to/notebook/directory")
```

Just be aware that running multiple instances of Emacs would lead to undefined results as on starting each instance would try to start its own instance of the jupyter server.

Other option would be to start a long running instance of jupyter outside of emacs and then have yours truly right some functions to automatically detect and log in to one of those instances.

**Comment by falematte** [comment]
Thank you. This works perfectly!
