### ISSUE TITLE
`ein:notebooklist-new-notebook-with-name` returns error

### ISSUE THREAD

**Issue by aronla** [millejoh/emacs-ipython-notebook#35]
The function `ein:notebooklist-new-notebook-with-name` returns "Wrong type argument: arrayp, nil."
This then also happens with for instance for `ein:junk-new`. Tried this on 3 different computers all giving the same result. Also happens when starting emacs using zeroein.el. 

* Installed from MELPA (two days ago)
* IPython 2.2.0
* Emacs 24.4
* Windows 8

Unfortunately, I'm too bad at lisp to understand what's going on. 
 :)

**Comment by millejoh** [comment]
Don't worry - I'm not too great at elisp either. I'm not sure what is happening. Sometimes this works and sometimes it does not. Asynchronous code can be difficult to debug. The arrayp error is probably because a global variable is nil when it should be something else. I will push a commit that tries to do a better job of handling that case.

Are you calling those commands from a notebooklist buffer, or somewhere else? They are meant to be called just from a notebooklist buffer, I believe, but I am going to try handling the case when they are not.

**Comment by aronla** [comment]
Thanks for your answer! I called it from other buffers I think, but when I do `ein:notebooklist-open` and then `ein:junk-new` it also throws an error albeit another one: `ein: [error] Content list call http://127.0.0.1:8888/api/notebooks/ failed with status abort.` It has now created a new notebook "Untitledx.ipynb" but not renamed it to "junk..." 

It would be very nice if this would work from other buffers as well! :)

**Comment by millejoh** [comment]
This works for my under IPython 3.0 - so I must have missed something in the code for renaming notebooks.

I think I have an idea of how to get those commands to work more generically - I will try to get something pushed in the next couple of days. Cheers.

**Comment by millejoh** [comment]
I just pushed a commit that should make this work better under IPython 2.x. Let me know if it works for you.

**Comment by aronla** [comment]
That's awesome! I can now call `ein:notebooklist-new-notebook-with-name` from anywhere with the correct result, but `ein:junk-new` still returns the same error. This is no big issue though...:)

Thank you very much for the great work!

**Comment by millejoh** [comment]
I'll take 1 and 1. Wish I knew why junk-new is failing. All it is doing is calling ein:notebooklist-new-notebook-with-name so if that is working than so just junk-new. Maybe you need to delete all your *.elc files?
