### ISSUE TITLE
ein killed my kernels

### ISSUE THREAD

**Issue by sam-s** [millejoh/emacs-ipython-notebook#384]
This morning I restarted emacs and tried to open my long-running precious notebooks.
I got these:
```
ein: [info] Kernel started: 8b21d610-00ca-4772-88bf-20d2662a7ec8
ein: [error] Error (wrong-type-argument sequencep t) on websocket action on-message (ws:wss://datasci-1.clearme.com:8888/api/kernels/8b21d610-00ca-4772-88bf-20d2662a7ec8/channels?session_id=0c69b531-ff2d-470c-bf2f-888038aa03d0).
Follow the link. [3 times]
ein: [info] Notebook session killed.
ein: [error] Error (wrong-type-argument sequencep t) on websocket action on-message (ws:wss://datasci-1.clearme.com:8888/api/kernels/8b21d610-00ca-4772-88bf-20d2662a7ec8/channels?session_id=0c69b531-ff2d-470c-bf2f-888038aa03d0).
ein: [info] Notebook session killed.
ein: [error] Error (wrong-type-argument sequencep t) on websocket action on-message (ws:wss://datasci-1.clearme.com:8888/api/kernels/8b21d610-00ca-4772-88bf-20d2662a7ec8/channels?session_id=0c69b531-ff2d-470c-bf2f-888038aa03d0). [2 times]
Quit
ein: [error] Error (wrong-type-argument sequencep t) on websocket action on-message (ws:wss://datasci-1.clearme.com:8888/api/kernels/8b21d610-00ca-4772-88bf-20d2662a7ec8/channels?session_id=0c69b531-ff2d-470c-bf2f-888038aa03d0). [14 times]
```
Both processes are now dead - and I lost several days worth of work.
Words fail me.

Is it possible to completely disable kernel kill functionality in ein?
I will `kill` the process if necessary myself.

**Comment by dickmao** [comment]
I am sorry you lost all that work.  We have all been there.  While I am appreciative of your active continued use of EIN (although in light of the circumstances, this may change very soon), notebooks were designed for quick-feedback exploration and not long-running estimations which are better served by noninteractive launchers.

From recent conversations, I am generally confused about your installation.  The strings "Kernel started" and "Notebook session killed" have not been in master since db2856f.

Suppose you are using `melpa-stable` which do contain those strings.  My reading of that code suggests `ein:kernel-kill` is executed only when clicking "Stop" or when explicitly requesting a restart, neither of which you did.
