### ISSUE TITLE
Ein randomly hangs.

### ISSUE THREAD

**Issue by melancholiac** [millejoh/emacs-ipython-notebook#404]
Ein hangs every 20-30 minutes, how do i can to find out why is this happening?

**Comment by millejoh** [comment]
Are you running on Windows? What is `gc-cons-threshold` set at? I've noticed my Windows emacs session pausing every so often and I suspect it is because the gc is running. I remember EIN tries to temporarily increase the gc threshold to improve performance while opening really large notebooks. It's very possible the temporary change is more of a permanent one.

I haven't had much time to fiddle around with this, but you might try decreasing the cons threshold (if it's been changed) and see if performance improves. It would be really useful if you can catch a profiler report (`M-x profiler-start`, then `M-x profiler-report`) of when the pause occurs!

**Comment by melancholiac** [comment]
> Is it the kind of hangs where you have to `C-g` out of it? Perhaps `M-: (setq debug-on-quit t)`.

i have to rerun emacs

**Comment by melancholiac** [comment]
> Are you running on Windows? What is `gc-cons-threshold` set at? I've noticed my Windows emacs session pausing every so often and I suspect it is because the gc is running. I remember EIN tries to temporarily increase the gc threshold to improve performance while opening really large notebooks. It's very possible the temporary change is more of a permanent one.
> 
> I haven't had much time to fiddle around with this, but you might try decreasing the cons threshold (if it's been changed) and see if performance improves. It would be really useful if you can catch a profiler report (`M-x profiler-start`, then `M-x profiler-report`) of when the pause occurs!

nope, linux

**Comment by melancholiac** [comment]
deleted 'delete-trailing-whitespaces from config, ein hangs no more
