### ISSUE TITLE
Extension not working on Ubuntu vivid with emacs 24.4.1 and ipython 3.1.0

### ISSUE THREAD

**Issue by brianmingus** [millejoh/emacs-ipython-notebook#51]
I am running Ubuntu vivid, with emacs 24.4.1 and ipython 3.1.0. I have checked out your emacs-ipython-notebook repository, and I am running lisp/zeroin.el

When I am in emacs, none of the ein: commands work at all.

**Comment by millejoh** [comment]
I, unfortunately, can't reproduce. How are you calling zeroein.el from the command line? I have a vagrant box running Ubuntu and have zeroein.el set to executable and just go lisp/zeroein.el.

Note that zeroein will download a number of dependencies and when it is done will automatically call ein:notebooklist-open. Are you at least seeing the prompt form port/url for getting the notebooklist? Also, anything of note in the *Messages* buffer?

**Comment by brianmingus** [comment]
@millejoh thanks for getting back to me. I am actually running on a Chromebook with crouton installed, and I have modified the lisp/zeroein.el scrip to read:

`":"; exec xiwi ${EMACS:-emacs} -Q -l "$0" "$@" # -*-emacs-lisp-*-`

xiwi just opens an app as a window in Chrome OS.  emacs opens, but I see no evidence that this emacs package is working.

I now notice that I see an error saying the Messages buffer is read only. Any idea on that?

**Comment by brianmingus** [comment]
I even ran `sudo lisp/zeroein.el` and I still get the `eval-buffer: Buffer is read-only: #<buffer *Messages*>` error.

**Comment by millejoh** [comment]
By design the [Messages](http://www.gnu.org/software/emacs/manual/html_node/elisp/Logging-Messages.html#Logging-Messages) buffer is read-only, so that behavior is expected. Can you try running zeroein.el from the terminal, i.e. without the `exec xiwi`? I just want to be confident that xiwi isn't doing something odd.

I would like to see the contents of the `*Messages*` buffer and, if it is present, the contents of the `*ein:log-all*` buffer.
