### ISSUE TITLE
connection to jupyter server over SSH from Windows

### ISSUE THREAD

**Issue by Pfedj** [millejoh/emacs-ipython-notebook#519]
Windows 10.
Emacs 27.0.50
Ein-20190416.1504
I would like to connect to remote server through SSH.  My settings:
```
(setq ein:console-executable (expand-file-name "C:/anaconda3/Scripts/"))
(setq ein:console-security-dir (expand-file-name "~/connection/"))
(setq ein:console-args '("--simple-prompt" "--ssh" "jupyter-remote"))
```
`"C:/anaconda3/Scripts/"` - this directory contains ipython.exe and jupyter.exe, `(setq ein:console-security-dir (expand-file-name "~/connection/"))` contains connection setting json, which I found on the server.
When I eval:
`M-x:ein:console-open`
==> Cannot find notebook to connect!
Could you help me to resolve this issue?

**Comment by dickmao** [comment]
I am unfamiliar with the `ein:console-open`.  It is not tested.

I just tried it and it didn't really work.  I would not be sad to see this functionality removed to avoid confusing users.

**Comment by AlphaAlgorithms** [comment]
Yes, please remove it .

**Comment by millejoh** [comment]
It may need to be better documented and thoroughly tested, but unless the code for this feature happens to be breaking other, more important parts of the code I cannot see any justification for its removal. Life is messy.

@pfedj - I think your problem is that `ein:console-executable` should be set to the absolute path of the jupyter executable (i.e. `C:/anaconda3/Scripts/jupyter.exe`). This is what I do on my windows setup and have no issues calling `ein:console-open` from an opened notebook buffer. Note that my settings for `ein:console-security-dir` and `ein:console-args` are blank.

**Comment by dickmao** [comment]
> Yes, please remove it .

You got it.
