### ISSUE TITLE
Refresh shared output buffer?

### ISSUE THREAD

**Issue by indigoviolet** [millejoh/emacs-ipython-notebook#534]
After `ein:shared-output-show-code-cell-at-point`, is there a way to refresh the shared buffer to get new output displayed?

**Comment by millejoh** [comment]
Currently, no. It is not obvious to me how to implement this directly either. The shared-output buffer is used by ob-ein and `ein:shared-output-eval-string` for evaluating code, potentially from multiple different kernels. Because of this the code cell in the shared output buffer, unlike in a notebook buffer, does not encapsulate any kernel information.

What I do is to place the code in an org buffer and evaluate it from there; the output goes to the shared output and if I have the two windows open side by side then I can get behavior approximating what you are asking for. I can also execute a bunch of cells at once (ala `org-babel-execute-subtree`) and sit and watch the shared buffer update over the many calls (useful when I am generating a bunch of graphs, but am too  impatient to wait for everything to finish and scroll through the org buffer).
