### ISSUE TITLE
Support authorizing in JupyterHub

### ISSUE THREAD

**Issue by krvkir** [millejoh/emacs-ipython-notebook#56]
I'm trying to use ein with jupyterhub (it's multiuser server for jupyter notebooks) and can't authorize in it (with ein:notebooklist-login).

PS I don't know will it be helpful but JupyterHub uses slightly different authorization page than Jupyter (with login field), and after authorization you get just regular Jupyter server.

PS I have very limited experience in emacs lisp but if you give me some clues where to look I'll try to implement the feature by myself.

**Comment by millejoh** [comment]
See #57 - all should be working now, at least with IPython/Jupyter 3.x. I'm not sure how all works with the current development versions.

**Comment by krvkir** [comment]
I meant not just Jupyter but JupyterHub. (This is of course not a bug but feature request :), and not very important one.)

**Comment by millejoh** [comment]
See #194 for current status. Has it really been two years? Gawd.

**Comment by millejoh** [comment]
As of 4f5f29d3516d687025ad9423dc98bcd202efed56 ein now has some support for jupyterhub. Check out the new command `ein:jupyterhub-connect`.

Note that you need to you need to be running the development version of jupyterhub. There is a bug in v0.7 that keeps ein from working. Otherwise let me know if you run into any issues!
