### ISSUE TITLE
ein:notebooklist-open can not be chosen.  

### ISSUE THREAD

**Issue by ofenerci** [millejoh/emacs-ipython-notebook#570]
When I try to run ´ein:notebooklist-open´. this command doesn't show. Instead, I can see the commands (`ein:notebook-open´ or ´ein:notebook-open-in-browser´) I wonder why this is so.

Emacs Version: 26
Operating System: Debian 10

**Comment by dickmao** [comment]
https://github.com/millejoh/emacs-ipython-notebook/blob/master/lisp/ein-notebooklist.el#L812-L813

`ein:notebooklist-open` is an autoloaded function, so it should "show" (if by "doesn't show" you mean the command is not available).  So then I must question your version of EIN which I don't know since you didn't follow the README to report this issue.

Also, you should not need to call that method as it is largely deprecated (again, please follow the README to operate EIN).
