### ISSUE TITLE
``src`` code blocks do not display plots

### ISSUE THREAD

**Issue by Nathan-Furnal** [millejoh/emacs-ipython-notebook#645]
Hi!

I've been trying to use ein but when I try to plot I only get a [...] :

![image](https://user-images.githubusercontent.com/45597572/72766746-8a335b00-3bf1-11ea-98d6-45f3cf6c1b5f.png)

what can I do to fix this ? 

Thanks

**Comment by millejoh** [comment]
Couple of checks:

 1. Does the code work in a notebook buffer (i.e. does it produce the expected plot image)?
 2. What happens when executing some simple code, like `print("Hello, how are you?")`.
 3. When executing from org what are the contents of the `*ein:shared-output*`?

For the session parameter I would use the full URL to the notebook, i.e. something like `http://localhost:8888/figs.ipynb`. The ellipsis means that ein thinks the python code is still executing - this could be happening because it hasn't figured out what notebook to open.
