### ISSUE TITLE
<IPython.core.display.HTML object>

### ISSUE THREAD

**Issue by indigoviolet** [millejoh/emacs-ipython-notebook#719]
Some functions from the library I'm using (`fastai2`) display `<IPython.core.display.HTML object>` instead of the HTML table that I see in the browser. Is there a way to fix this?

In the browser it looks like:

![image](https://user-images.githubusercontent.com/114010/82770346-15fe0380-9ded-11ea-8309-af9c3ff75ce5.png)

**Comment by Zar-rok** [comment]
# Problem

I'm currently using [pyAgrum](https://pyagrum.readthedocs.io/en/0.18.1/) which also display `<IPython.core.display.HTML object>` instead of the HTML content.

And I see that, when I look at the raw notebook, the content I except to see is under the `output.data.text/html` entry and the displayed content is in `output.data.text/plain`. But when I try to display a plot with `matplotlib`:
```python
import matplotlib.pyplot as plt
plt.plot((1, 2), (3, 4))
```
The the plot is displayed as except and the content is under the `output.data.image/svg+xml` entry.

# Manual fix

Thus I tried to manually rename `output.data.text/html` into `output.data.image/svg+xml` and it finally displayed the content I expect!

# Research

I am not familiar with Lisp in general, but I found in the documentation the [`ein:output-type-preference`](https://millejoh.github.io/emacs-ipython-notebook/#ein:output-type-preference) variable which seems to defined the priority between the entries. But it is now deprecated (why?):
https://github.com/millejoh/emacs-ipython-notebook/blob/ccbed30c991623d56a310d02c76f03d571e90e82/lisp/ein-cell.el#L867

Then, I searched the piece of code which define this priorities and it's look like this macro is what I must (perhaps) edit:
https://github.com/millejoh/emacs-ipython-notebook/blob/0e6877cdc25a7a739b1f7299871950fbf18da928/lisp/ein-output-area.el#L153-L159

# Question

I've redefined the `ein:output-area-case-type` macro in my Doom Emacs `config.el` file, without any success.

**I would like to know how this priority list can be customized?**

Thank you in advance!

**Comment by dickmao** [comment]
Diagnosis of zar-rok is spot on.
