### ISSUE TITLE
[error] request--callback: peculiar error: 500

### ISSUE THREAD

**Issue by zeta-00** [millejoh/emacs-ipython-notebook#723]
Invalid face reference: diff-added [71 times]
Invalid face reference: diff-changed [2 times]
Invalid face reference: diff-added [128 times]
Invalid face reference: diff-changed [2 times]
ein: [info] ein:jupyter-server--run: /nix/store/58fyx5yd56ix3x01xnalyg15zqjw7v36-ihaskell-with-packages/bin/jupyter notebook --notebook-dir=~/.ihaskell/notebooks/ --no-browser
ein: [info] Login to http://127.0.0.1:8888 complete.
ein: [info] Worksheet Untitled9.ipynb is ready
[error] request--callback: peculiar error: 500 [3 times]

**Comment by zeta-00** [comment]
i also enabled emacs debugger, and know other errors were thrown, so i'm not sure how to troubleshoot this error?

ein seems to be working fine, but when i try to open a `New Notebook`, this error gets thrown?

how do i troubleshoot this?

also, i was messing around with the emacs-jupyter package a while back, so maybe i messed up something in ein by accident, at this point i have no idea?

**Comment by dickmao** [comment]
Your jupyter instance is responding with 500 Internal Server Error.

Your best hope is that it's benign (it often is).  Otherwise you'll have to replicate the curl calls that EIN makes to see which one triggers 500 (you can see those by turning on `M-x ein:dev-start-debug`, reproducing the error, and looking at `M-x ein:log-pop-to-request-buffer`).  It's an onerous debugging task best avoided if possible.
