### ISSUE TITLE
Saved notebooks are untrusted

### ISSUE THREAD

**Issue by jluttine** [millejoh/emacs-ipython-notebook#76]
When saving notebooks, the notebook server reports:

```
[W ... NotebookApp] Saving untrusted notebook blahblahblah.ipynb
```

This provides some details about the security model:

https://ipython.org/ipython-doc/3/notebook/security.html#the-details-of-trust

Any idea if this could be fixed easily? I suppose the problem is in this Emacs extension?

**Comment by millejoh** [comment]
In theory you should be able to call `ipython trust <notebook>` at the command line and have this work. The web interface also has a "Trust Notebook" command, which I assume does something similar to callling `ipython trust <notebook>.`

On one machine I have this seems to work. On another it does not. The fix is probably easy, but understanding the issue in order to find the fix may not.
