### ISSUE TITLE
Compatibility with Jupyter 3.0

### ISSUE THREAD

**Issue by nakkaya** [millejoh/emacs-ipython-notebook#803]
In issue #783 there was talk of `lab` not working with `ein` however I used to have a docker container running `jupyter lab` that I could connect to using `ein` without any issues. The other day I rebuilt the container which installed the latest version of `jupyter`  `3.X` that is causing the `api error`. I am guessing this is not related to running `lab` or `notebook` but new version has changed the api.

**Comment by danielfleischer** [comment]
I get 

> error in process sentinel: if: Api 1 unsupported
> error in process sentinel: Api 1 unsupported

Jupyter lab version 3.1.4 (dev), 3.0.16 (app)

**Comment by kendatsuba** [comment]
It seems that `ein` is picking `jupyter_server` version (`1.11.1` as of now) as the notebook/kernel api version. This gives `ein` the impression that the api version is lower than 2 and since versions lower than 1 are not supported it fails with that error. The `jupyter` messaging api however is substantially unchanged:

https://jupyter-client.readthedocs.io/en/stable/messaging.html

If you change this line:

https://github.com/millejoh/emacs-ipython-notebook/blob/0600c286bd7b0812f4908d7df1be279b6b65923f/lisp/ein-kernel.el#L64

to

```elisp
:api-version 5
```

it should work as a workaround.

**Comment by martin-liu** [comment]
@dickmao Wow, thanks for quick action! 
But I tried several different Jupyter lab versions and some of them have different description (from `jupyter-server`) which will fail the regexp check.

Created a simple PR https://github.com/millejoh/emacs-ipython-notebook/pull/811 to fix that, can you have a check?
