### ISSUE TITLE
Unable to configure output type preferences

### ISSUE THREAD

**Issue by memeplex** [millejoh/emacs-ipython-notebook#813]
The documentation references `ein:output-type-preference` and `ein:output-type-prefer-pretty-text-over-html`, none of which exist. According to git blame `ein:output-type-preference` was flagged as obsolete 2 years ago. How should I change the output preferences then?

A more general comment and I don't want to sound harsh but why are you linking documentation that is so outdated without any warning on what to expect?

**Comment by dickmao** [comment]
I'll admit the "README" imperative is on balance a sham, much as most advertising, print and televised, exhorting us to do something we otherwise wouldn't also disproportionately benefit the seller more than the buyer.

But this README did [contain a nugget](https://github.com/millejoh/emacs-ipython-notebook/blob/master/README.rst?plain=1#L12-L13) that would have mitigated your indignation:

> No require statements, e.g. ``(require 'ein)``, are necessary, contrary to the
`prevailing documentation`_, which should be disregarded.

The problem is I do not own https://millejoh.github.io/emacs-ipython-notebook, the author of which has  assumed an obstinate stance against my heavy-handed request https://github.com/millejoh/emacs-ipython-notebook/issues/732#issuecomment-668653000 to retire his documentation, understandably out of spite for my annexing of what was once his pet project (although to be fair, he in turn had commandeered it from the original author https://github.com/tkf/emacs-ipython-notebook).
