### ISSUE TITLE
This package is an utter mess

### ISSUE THREAD

**Issue by danielkrajnik** [millejoh/emacs-ipython-notebook#877]
1. Opening files takes forever
2. Once opened workspace is cluttered split into three buffers
3. Images don't show
4. Buffers don't show up
5. crashes

This is an embarrassment, I'm voting to remove this package from doom emacs and looking for someone competent to fork it instead.

**Comment by haschka** [comment]
You should know that people write packages like these in their spare time and give them away for free. As such they are offered to you for free. If you feel unhappy about it you can always propose a patch, change the code. 

I guess critique is fine in order to know what has to be improved. But statements like, this is an embarrassement, or blaming someone who does work for free of charge and gives it away for free of being incompetent will not help anyone, worse will demotivate the author and chances are far fewer that you get things as you want them. If you feel competent, then please be so kind and propose patches with code in order to levetate the problems you have with this package

About rendering an ipynb file directly without starting a server, personnally, and I am far from being the author of this package, I think this would be an utter mess. I actually like to connect to remote or local servers, have processes separated. From the inner workings rendering an ipynb is quite different then communicating with it through the server. I definatly get the authors point here and I guess he should leave it as it is for that part.

**Comment by danielkrajnik** [comment]
thank you for sharing a constructive criticism, I've closed the issue. Can I ask you how long does it usually take you to open a single .ipynb file? I found this time significantly longer on ein that running a `jupyter notebook` from a command line or in vscode.

vscode in particular solved this issue by not starting the server until you run any of the code cells, so initally it's a read-only rendering. Is it something that you've set up in emacs as well by any chance?
