### ISSUE TITLE
Bookmarked Notebooks

### ISSUE THREAD

**Issue by risantos** [millejoh/emacs-ipython-notebook#99]
Hello,

Is there a way to bookmark notebooks or notebook directories within ein?
Like you can bookmark files with `C-x r l` but for .ipynb files, connected through ein.

When opening them within my default browser (to see how they show up before publishing/sending anywhere/to someone), I just save them to Bookmarks, either a notebook or a file with them. (since I allways open Jupyter in the $HOME directory, the address is the same)

If this isn't already a feature, I would like to suggest it for enhancement.

Thanks.

**Comment by millejoh** [comment]
An interesting idea. You can't bookmark a notebook buffer at the moment because the buffer does not represent a file. Some time ago notebook buffer's presented themselves as files, but it resulted in some subtle bugs and so I had to disable. I will have to take a closer look at how bookmarks work and see if maybe there is a way around this problem.

Note that you can store links to notebook buffers in [org files](http://millejoh.github.io/emacs-ipython-notebook/#org-mode-integration).

**Comment by risantos** [comment]
Thanks for the enlightenment about org-mode integration. It is very useful to have quick access to the buffers from my main org-mode file (which is my emacs default opening buffer).

Nevertheless, the suggestion still stands, as I find that I can't store a directory while on:
`*ein: notebooklist 8888*` , where emacs returns: 
> No method for storing a link from this buffer

Although this presents a fantastic solution for previously-opened notebooks, saving a lot of time from browsing directories, I am imagining a command like: `ein:notebook-bookmarks` or an extra menu in ein:notebooklist-open, like bellow the options, with a "Bookmarked" Directories and notebooks

**Comment by dickmao** [comment]
I've no intention to work on this.  Sorry.

**Comment by yefeiyu** [comment]
I hope this can become ture.
